### ISSUE TITLE
Nintendo Switch Ingest Module 

### ISSUE THREAD

**Issue by upintheairsheep** [sleuthkit/autopsy_addon_modules#18]
modux/Nintendo-Switch-Forensics

**Comment by markmckinnon** [comment]
Not sure what this issue is.  Closing it, if you feel it needs to be reopened then feel free to reopen it.

**Comment by upintheairsheep** [comment]
> Not sure what this issue is. Closing it, if you feel it needs to be reopened then feel free to reopen it.
https://GitHub.com/modux/Nintendo-Switch-Forensics

**Comment by markmckinnon** [comment]
If you want this added to the repo then go and fill out the info to add it to the repo. It is up to the individual to do that not the maintainers of this repo. If you have any questions let me know.
